env:
  global:
  - REFTEST_IGNORE_TRANSIENT=YES
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
matrix:
  include:
    - sudo: false
      dist: trusty
      language: python
      python: "2.7"
      env: BRBASE=7.0 BRPVD=master BRPVA=master PROF=deb9
      install: ./.ci/travis-linux-prepare.sh
      script: ./.ci/travis-linux-build.sh

    - sudo: false
      dist: trusty
      language: python
      python: "2.7"
      env: BRBASE=3.16 BRPVD=master BRPVA=master PROF=deb8
      install: ./.ci/travis-linux-prepare.sh
      script: ./.ci/travis-linux-build.sh

    - sudo: false
      dist: trusty
      language: python
      python: "2.7"
      env: BRBASE=3.15 BRPVD=master BRPVA=master PROF=deb8
      install: ./.ci/travis-linux-prepare.sh
      script: ./.ci/travis-linux-build.sh

    - sudo: false
      dist: trusty
      language: python
      python: "2.7"
      env: BRBASE=3.14 BRPVD=master BRPVA=master PROF=deb8
      install: ./.ci/travis-linux-prepare.sh
      script: ./.ci/travis-linux-build.sh

    - sudo: required
      language: python
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp27-cp27m
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build ${PYVER}-manylinux1_x86_64

    - sudo: required
      language: python
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp27-cp27mu
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build ${PYVER}-manylinux1_x86_64

    - sudo: required
      language: python
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp34-cp34m
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build ${PYVER}-manylinux1_x86_64

    - sudo: required
      language: python
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp35-cp35m
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build ${PYVER}-manylinux1_x86_64

    - sudo: required
      language: python
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PYVER=cp36-cp36m
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build ${PYVER}-manylinux1_x86_64

    - sudo: required
      language: python
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PYVER=cp27-cp27m
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build ${PYVER}-manylinux1_i686

    - sudo: required
      language: python
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PYVER=cp27-cp27mu
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build ${PYVER}-manylinux1_i686

    - sudo: required
      language: python
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PYVER=cp34-cp34m
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build ${PYVER}-manylinux1_i686

    - sudo: required
      language: python
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PYVER=cp35-cp35m
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build ${PYVER}-manylinux1_i686

    - sudo: required
      language: python
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PYVER=cp36-cp36m
      install: docker pull $DOCKER_IMAGE
      script: docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD "/opt/python/$PYVER/bin/python" /io/cibuild.py docker prepare build ${PYVER}-manylinux1_i686

    - os: osx
      language: generic
      env: PYTHON=python2 PYVER=2.7 URL=https://www.python.org/ftp/python/2.7.15/python-2.7.15-macosx10.6.pkg
      install:
        - ./travis-osx.sh
        - python2 cibuild.py prepare
      script:
        - python2 cibuild.py build cp27-cp27m-macosx_10_6_intel.macosx_10_6_x86_64

    - os: osx
      language: generic
      env: PYTHON=python3 PYVER=3.6 URL=https://www.python.org/ftp/python/3.6.7/python-3.6.7-macosx10.6.pkg
      install:
        - ./travis-osx.sh
        - python3 cibuild.py prepare
      script:
        - python3 cibuild.py build cp36-cp36m-macosx_10_6_intel.macosx_10_6_x86_64

after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a -n "$TWINE_USERNAME" ] ; then
      echo "Deploying"
      ${PYTHON:-python} -m pip install twine
      ${PYTHON:-python} -m twine upload --skip-existing dist/*.tar.* dist/*.whl || true
    fi
